### PR TITLE
add len parameter in update() of resty.md5

### PR DESCRIPTION
**Pull request by sjnam**
When I use  _M.update(self, s) in resty.md5, I had an case when len is not #s.
so, how about the following?

function _M.update(self, s, len)
    return C.MD5_Update(self._ctx, s, len or #s) == 1
end

### CODE REVIEW

**Comment by agentzh** [comment]
@sjnam Thanks for the patch! But will you add a test case to the existing test suite too? Thanks!

**Comment by sjnam** [comment]
@agentzh I added a test case. Thanks!

**Comment by agentzh** [comment]
@sjnam Awesome! I'll look into this as soon as I can manage :) Thanks a lot!

**Comment by agentzh** [comment]
@sjnam Mind to add a note to README as well? ;)

**Comment by sjnam** [comment]
@agentzh 
I just add one comment line and small change to already given test code in README.

**Comment by agentzh** [comment]
@sjnam Cool. Thanks!

**Review by zhuizhuhaomeng — APPROVED** [review]

**Pull request closed without merging**
